// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebServerCloud.Data;

namespace WebServerCloud.Migrations
{
    [DbContext(typeof(WebServerCloudContext))]
    [Migration("20210915193145_initia")]
    partial class initia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebServerCloud.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Cedevole")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iniziali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Molle")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Normale")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrimoPortatore")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("WebServerCloud.Models.Ordine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AudioProtesistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cedevole")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("Cliente_DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cliente_Iniziali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cliente_PrimoPortatore")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiniFit_Fitting")
                        .HasColumnType("int");

                    b.Property<string>("MiniFit_Lato")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MiniFit_Mould")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiniFit_Tip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Molle")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Normale")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PFM_Fitting")
                        .HasColumnType("int");

                    b.Property<string>("PFM_Lato")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("PFM_Versione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PFM_Wire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpedizioneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ventilazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("VideoName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AudioProtesistaId");

                    b.HasIndex("SpedizioneId");

                    b.ToTable("ordini");

                    b.HasCheckConstraint("CK_DATI_Ventilazione", "Ventilazione in ('D','S','E','N')");

                    b.HasCheckConstraint("CK_Utente_Molle", "Molle in ('D','S','E','N')");

                    b.HasCheckConstraint("CK_Utente_Cedevole", "Cedevole in ('D','S','E','N')");

                    b.HasCheckConstraint("CK_Utente_Normale", "Normale in ('D','S','E','N')");
                });

            modelBuilder.Entity("WebServerCloud.Models.Spedizione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("tenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("tenantId");

                    b.ToTable("Spedizioni");
                });

            modelBuilder.Entity("WebServerCloud.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Cellulare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stampante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("WebServerCloud.Models.Ordine", b =>
                {
                    b.HasOne("WebServerCloud.Models.Tenant", "AudioProtesista")
                        .WithMany()
                        .HasForeignKey("AudioProtesistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServerCloud.Models.Spedizione", "Spedizione")
                        .WithMany()
                        .HasForeignKey("SpedizioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebServerCloud.Models.Spedizione", b =>
                {
                    b.HasOne("WebServerCloud.Models.Tenant", "tenant")
                        .WithMany("Spedizioni")
                        .HasForeignKey("tenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
